config/routes.rb
PatriotPoisk::Application.routes.draw do
  get "sites/add" => "pages#add_site", :as => :add_site
  resources :sites

  root "search#index"
  get "results" => "search#results"
  get "opensearch.xml" => "search#open_search"

  get "stats" => "pages#stats"
  get "about" => "pages#about"

end

app/models/site.rb
class Site < ActiveRecord::Base
  validates :address, :uniqueness => true

  def domain_without_www
    address.gsub(/^www./, "")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def stats
  end

  def sites
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def index
    expires_in 1.day, :public => true
  end

  def results
  end

  def open_search
    response.headers["Content-Type"] = 'application/opensearchdescription+xml'
    render :layout => false
  end
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  http_basic_authenticate_with :name => "SergeiUdalov", :password => "lowkick", :except => :index
  before_action :set_site, only: [:show, :edit, :update, :destroy]

  # GET /sites
  # GET /sites.json
  def index
    expires_in 1.hour, :public => true

    date = 7.days.ago
    @new_sites = Site.where("created_at >= ?", date)
    @sites = Site.all
  end

  # GET /sites/1
  # GET /sites/1.json
  def show
  end

  # GET /sites/new
  def new
    @site = Site.new
  end

  # GET /sites/1/edit
  def edit
  end

  # POST /sites
  # POST /sites.json
  def create
    @site = Site.new(site_params)

    respond_to do |format|
      if @site.save
        format.html { redirect_to @site, notice: 'Site was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site }
      else
        format.html { render action: 'new' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sites/1
  # PATCH/PUT /sites/1.json
  def update
    respond_to do |format|
      if @site.update(site_params)
        format.html { redirect_to @site, notice: 'Site was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sites/1
  # DELETE /sites/1.json
  def destroy
    @site.destroy
    respond_to do |format|
      format.html { redirect_to sites_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site
      @site = Site.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_params
      params.require(:site).permit(:address)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ru">
<head>
  <title>Сусанин: найдется дорога!</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
  <link rel="icon" href="/favicon.ico" type="image/x-icon">
  <link title="Сусанин: найдется дорога!" type="application/opensearchdescription+xml" rel="search" href = "/opensearch.xml">

  <meta content="Поисковик, поисковая система, НОД, национально-освободительное движение, " name="keywords"></meta>

  <meta name="description" content="" /> 

  <meta property="og:type" content="article" /> 
  <meta property="og:url" content="http://susanin.russianpulse.ru" /> 
  <meta property="og:title" content="Поисковик «Сусанин»: найдется дорога!" /> 
  <meta property="og:image" content="<%= asset_url("promo.jpeg") %>" /> 
  <link rel="image_src" href="<%= asset_url("promo.jpeg") %>" />

  <meta property="og:description" content="Поисковая система с патриотическим фильтром. Сюда не попадают либералы и прочие русофобы" />
  <meta name="twitter:card" content="Поисковая система с патриотическим фильтром. Сюда не попадают либералы и прочие русофобы" />

  <%= stylesheet_link_tag    "//yandex.st/bootstrap/3.0.3/css/bootstrap.min.css", media: "all" %>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

<div class="container">
  <div class="col-md-8 col-md-offset-2" style="height: 100%">
    <table style="height: 100%; width:100%">
      <tr style="height: 100px">
        <td>
          <%= link_to_unless_current image_tag("logo.jpeg", :alt => "Патриотичная сторона рунета"), root_path, :title => "Патриотичная сторона рунета" %>
        </td>
      </tr>
      <tr>
        <td>
          <%= yield %>
        </td>
      </tr>
      <tr style="height: 50px">
        <td valign="bottom">
          <table class="footer" style="width: 100%">
            <tr>
              <td>
                &copy; 2014 «<a href="/" rel="nofollow">Сусанин</a>»
                <a href="/sites" class="padding">Сайты</a>
                <a href="/about" class="padding">О проекте</a>


                <!-- Участник рейтинга сайтов НОД http://nodtop.russianpulse.ru/ -->
                <span id="nodtop_counter_container" class="padding"></span>
                <script>
window.nodtop_cnt = {
id: "33Cuzw",
    container_id: "nodtop_counter_container",
    type: 1
}
                </script>
                <script src="//sergio-fry.github.io/nodtop-counter-site/counter/v1/cnt.js" defer></script>

      

              </td>
              <td align="right">
                Автор: <a href="http://www.sergei-udalov.ru" target="_blank">Сергей Удалов</a>
              </td>
            </tr>
          </table>
        </td>
      </tr>
      <tr style="height: 20px">
        <td>
        </td>
      </tr>
    </table>
  </div>
</div>

  <div class="hidden"><img src="http://s05.flagcounter.com/count/LTb3/bg_FFFFFF/txt_000000/border_CCCCCC/columns_3/maxflags_250/viewers_3/labels_1/pageviews_0/flags_0/" alt="Flag Counter" border="0"></div>

  <%= javascript_include_tag "//yandex.st/bootstrap/3.0.3/js/bootstrap.min.js" %>
  <%= render :partial => 'shared/counter' %>
</body>
</html>

app/views/pages/about.html.erb
<h1>О проекте</h1>

<p>«Сусанин» - это не обычная поисковая система. В отличие от Яндекс или Google, «Сусанин» ищет только по <a href="/sites">выбранным сайтам</a>. Специализируется «Сусанин» на новостях, событиях и истории. Но зачем такие ограничения?</p>

<p>Для многих патриотов не секрет, что в России идет информационная война. С распада СССР и утилизации нашей пропагандистской машины, на смену приходит пропаганда с Запада. Уже более 20 лет происходит информационное избиение России и русского народа в целом. Именно поэтому нужно фильтровать область поиска.</p>

<h2>Какие сайты попадают в поиск?</h2>
<p>Которые не являются русофобскими. Вы предлагаете сайты, а я одобряю или отклоняю.

Изначально буду считать, что весь рунет поражен. И только избранные сайты, один за одним буду включать в одобренный список.</p>

<h2>Отказ от ответственности</h2>
<ol>
  <li>Автор поисковой системы никак не связан с содержимых сайтов, которые отображаются в поисковиках.</li>
  <li>«Сусанин» вводит жесткие ограничения на включение сайтов в список. Никакой демократии, да.</li>
</ol>

<h2>Как работает поиск?</h2>

<p>Поиск работает на <a href="http://site.yandex.ru/" target="_blabk">движке Яндекс</a>. Я только составил каталог сайтов, по которому происходит поиск. Каждый желающий может создать свой "белый список" сайтов - и попросить Яндекс искать только по нему. Если же Вам понравится мой список - я буду только рад.</p>

<h2>Ссылки</h2>

<ul>
  <li><a href="/stats" class="padding">Статистика</a></li>
  <li><a href="http://www.russianpulse.ru/blogs/susanin" class="padding" target="_blank">Блог</a></li>
</ul>

<br />
<br />
<p class="pull-right">С уважением, <a href="http://www.sergei-udalov.ru">Сергей Удалов</a></p>

app/views/pages/add_site.html.erb
<h1>Добавить сайт</h1>

<p>Каждый сайт, прежде чем попасть в поисковую систему «Сусанин», проходит ручную модерацию. Критерии отбора субъективные. Главным критерием является отсутствие на сайте русофобства, вредных проявлений либерализма, национализма и т.д.. Ничто противозаконное нам также не нужно.</p>

<p>Предложенные сайты публикуйте в комментариях.</p>
<br />
<br />


<!-- Put this script tag to the <head> of your page -->
<script type="text/javascript" src="//vk.com/js/api/openapi.js?105"></script>

<script type="text/javascript">
  VK.init({apiId: 4202374, onlyWidgets: true});
</script>

<!-- Put this div tag to the place, where the Comments block will be -->
<div id="vk_comments"></div>
<script type="text/javascript">
VK.Widgets.Comments("vk_comments", {limit: 10, width: "520", attach: "*"});
</script>

app/views/pages/sites.html.erb
<h1>Сайты</h1>
<p>В поиске участвуют только отобранные сайты. Полный список:</p>

<pre>
21russia.ru
27sev.com
andreyfursov.ru
beriozka-rus.livejournal.com
continentalist.ru
contrpost.com
dbelyaev.ru
eot.su
evrazia.org
file-rf.ru
fpvestnik.ru
gazeta.eot.su
ipolk.ru
kremlin.ru
mixednews.ru
nstarikov.ru
oko-planet.su
patriot-blogpost.ru
pereformat.ru
perevodika.ru
politikus.ru
poznavatelnoe.tv
r-v-s.su
ruskline.ru
rusnod.ru
ruspravda.info
russia-review.ru
russian.rt.com
ruxpert.ru
sdelanounas.ru
telegrafist.org
voprosik.net
worldcrisis.ru
www.fondsk.ru
www.odnako.org
www.russianpulse.ru
www.russiapost.su
www.sdelanounih.ru
www.sergei-udalov.ru
www.sevastopol.su
www.specnaz.ru
www.warandpeace.ru
концептуал.рф
</pre>

<p><%= link_to "Предложить сайт", add_site_path, :class => "btn btn-primary" %></p>

app/views/pages/stats.html.erb
<h1>Статистика</h1>
<p>
<a href="http://top.mail.ru/visits?id=2483817#back=30" target="_blank"><img src="http://top.mail.ru/visits.png?id=2483817&period=0&date=&back=30&" style="border: 0px" /></a>
</p>
<h2>Страны</h2>
<p>
  <a href="http://info.flagcounter.com/LTb3"><img src="http://s05.flagcounter.com/count/LTb3/bg_FFFFFF/txt_000000/border_CCCCCC/columns_3/maxflags_250/viewers_3/labels_1/pageviews_0/flags_0/" alt="Flag Counter" border="0"></a>
</p>

app/views/search/_search_form.html.erb
<div class="ya-site-form ya-site-form_inited_no" onclick="return {'action':'/results','arrow':false,'bg':'transparent','fontsize':16,'fg':'#000000','language':'ru','logo':'rb','publicname':'Поиск патриота','suggest':true,'target':'_self','tld':'ru','type':2,'searchid':2125716,'webopt':false,'websearch':false,'input_fg':'#000000','input_bg':'#ffffff','input_fontStyle':'normal','input_fontWeight':'normal','input_placeholder':null,'input_placeholderColor':'#000000','input_borderColor':'#999999'}"><form action="http://yandex.ru/sitesearch" method="get" target="_self"><input type="hidden" name="searchid" value="2125716"/><input type="hidden" name="l10n" value="ru"/><input type="hidden" name="reqenc" value=""/><input type="text" name="text" value=""/><input type="submit" value="Найти"/></form></div><style type="text/css">.ya-page_js_yes .ya-site-form_inited_no { display: none; }</style><script type="text/javascript">(function(w,d,c){var s=d.createElement('script'),h=d.getElementsByTagName('script')[0],e=d.documentElement;if((' '+e.className+' ').indexOf(' ya-page_js_yes ')===-1){e.className+=' ya-page_js_yes';}s.type='text/javascript';s.async=true;s.charset='utf-8';s.src=(d.location.protocol==='https:'?'https:':'http:')+'//site.yandex.net/v2.0/js/all.js';h.parentNode.insertBefore(s,h);(w[c]||(w[c]=[])).push(function(){Ya.Site.Form.init()})})(window,document,'yandex_site_callbacks');</script>

<% if auto_focus %>
  <%= javascript_tag do %>
    var set_focus = function() {
      $(".ya-site-form input[name='text']").focus();
    }

    $(function() {
      setTimeout(set_focus, 500);
      setTimeout(set_focus, 1000);
      setTimeout(set_focus, 3000);
    });
  <% end %>
<% end %>

app/views/search/index.html.erb
<%= render :partial => 'search_form', :locals => { :auto_focus => true } %>

app/views/search/open_search.erb
<?xml version="1.0" encoding="UTF-8"?>
<OpenSearchDescription xmlns="http://a9.com/-/spec/opensearch/1.1/">
  <ShortName>Сусанин</ShortName>
  <Description>Найдется дорога!</Description>
  <InputEncoding>UTF-8</InputEncoding>
  <Image height="16" width="16" type="image/x-icon">http://susanin.russianpulse.ru/favicon.ico</Image>
  <Url type="text/html" template="http://susanin.russianpulse.ru/results?searchid=2125716&amp;text={searchTerms}&amp;web=0"/>
  <Url type="application/x-suggestions+json" method="GET" template="http://suggest.yandex.ru/suggest-ff.cgi?part={searchTerms}"/>
</OpenSearchDescription>

app/views/search/results.html.erb
<%= render :partial => 'search_form', :locals => { :auto_focus => false } %>
<div>
  <div id="ya-site-results" onclick="return {'tld': 'ru','language': 'ru','encoding': '','htmlcss': '1.x','updatehash': true}"></div><script type="text/javascript">(function(w,d,c){var s=d.createElement('script'),h=d.getElementsByTagName('script')[0];s.type='text/javascript';s.async=true;s.charset='utf-8';s.src=(d.location.protocol==='https:'?'https:':'http:')+'//site.yandex.net/v2.0/js/all.js';h.parentNode.insertBefore(s,h);(w[c]||(w[c]=[])).push(function(){Ya.Site.Results.init();})})(window,document,'yandex_site_callbacks');</script>

</div>
<div>
  Поискать «<strong><%= params[:text] %></strong>» в других поисковых системах: 
  <%= link_to "Яндекс", "http://yandex.ru/yandsearch?text=#{params[:text]}", :target => "_blank" %>
  <%= link_to "Google", "http://www.google.ru/search?ie=UTF-8&hl=ru&q=#{params[:text]}", :target => "_blank" %>
  <%= link_to "Mail.ru", "http://go.mail.ru/search?mailru=1&q=#{params[:text]}", :target => "_blank" %>
  <%= link_to "Bing", "http://www.bing.com/search?q=#{params[:text]}", :target => "_blank" %>
</div>

app/views/shared/_counter.html.erb
<!-- Rating@Mail.ru counter -->
<script type="text/javascript">//<![CDATA[
var _tmr = _tmr || [];
_tmr.push({id: "2483817", type: "pageView", start: (new Date()).getTime()});
(function (d, w) {
 var ts = d.createElement("script"); ts.type = "text/javascript"; ts.async = true;
 ts.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//top-fwz1.mail.ru/js/code.js";
 var f = function () {var s = d.getElementsByTagName("script")[0]; s.parentNode.insertBefore(ts, s);};
 if (w.opera == "[object Opera]") { d.addEventListener("DOMContentLoaded", f, false); } else { f(); }
 })(document, window);
//]]></script><noscript><div style="position:absolute;left:-10000px;">
    <img src="//top-fwz1.mail.ru/counter?id=2483817;js=na" style="border:0;" height="1" width="1" alt="Рейтинг@Mail.ru" />
</div></noscript>
<!-- //Rating@Mail.ru counter -->

app/views/sites/_form.html.erb
<%= form_for(@site) do |f| %>
  <% if @site.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site.errors.count, "error") %> prohibited this site from being saved:</h2>

      <ul>
      <% @site.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_field :address %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sites/edit.html.erb
<h1>Editing site</h1>

<%= render 'form' %>

<%= link_to 'Show', @site %> |
<%= link_to 'Back', sites_path %>

app/views/sites/index.html.erb
<h1>Сайты</h1>

<% if @new_sites.present? %>
Новые сайты:
<pre>
  <% @new_sites.order(:address).each do |site| %>
<%= site.domain_without_www %> - добавлен <%= site.created_at.strftime("%Y/%m/%d") %>
  <% end %>
</pre>
<% end %>

<p>В поиске участвуют только отобранные сайты. Полный список:</p>

<pre>
  <% @sites.sort_by(&:domain_without_www).each do |site| %>
<%= site.domain_without_www %>
  <% end %>
</pre>

<p><%= link_to "Предложить сайт", add_site_path, :class => "btn btn-primary" %></p>

app/views/sites/new.html.erb
<h1>New site</h1>

<%= render 'form' %>

<%= link_to 'Back', sites_path %>

app/views/sites/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @site.address %>
</p>

<%= link_to 'Edit', edit_site_path(@site) %> |
<%= link_to 'Back', sites_path %>